### ISSUE TITLE
exit always returns the lookup of exit before actually exiting 

### ISSUE THREAD

**Issue by Bhargav-Rao** [maxrandolph/UrbanWiz#1]
Whenever we want to end the program and type `exit`, it returns the UD meaning of exit before leaving the program. 

This can be changed by using `while True:` and `if x=="exit" : break` after receiving the user input. You can even add another check if the user really wants to search for _exit_. 
<sub> Though the rarest of the rare cases, we can't just assume that the user is intelligent</sub>

---

Regards and Happy Coding

**Comment by maxrandolph** [comment]
Thanks, will change :+1:
